DataTracker/js/controllers/activities-controller.js, DataTracker/js/controllers/controllers.js, DataTracker/js/controllers/dataedit-controllers.js, DataTracker/js/controllers/import-controllers.js, DataTracker/js/controllers/modals-controller.js, DataTracker/js/services.js, DataTracker/partials/dataset-import.html, DataTracker/partials/grid-validation-error-box.html
Improve validation for importing fishermen interviews.
-When interview present, fisherman must be present also
-When fisherman cannot be found, set it to UNKNOWN
-When location name cannot be found, flag as error
=> Fisher upd

DataTracker/js/main.js
Also must add a line to our private config.js with the google analytics identifier (since we don't track in git):
var ANALYTICS_CODE = 'UA-105142901-1'; //this should be your own analytics code for google analytics.
=> send hit to analytics anytime location changes

.gitignore, DataTracker/js/controllers/login-controller.js
This update encrypts the user's password, so that when someone views it in the Network tab of the debugger, it is no longer in plain text.
=> Upd authent

DataTracker/js/controllers/controllers.js, DataTracker/js/controllers/login-controller.js, DataTracker/js/controllers/modals-controller.js, DataTracker/js/directives/Map.js, DataTracker/js/init.js, DataTracker/js/main.js, DataTracker/js/services.js
Fixes the following issues.
-CRPP:  When you created a Subproject, checking Yes to add a document, and added the new document right away, when you clicked on the Subproject, the data in the Correspondence Event looked weird; it works properly now
-Habitat:  When you deleted a Habitat Item, and clicked on the Site again, it would not show the Habitat Item cleared (removed); it does now
-Sometimes a user could not add data to a project they owned; it works properly now
=> Fix cr hab and new user issue

DataTracker/js/controllers/import-controllers.js
Added else branch, for when FishCount != null and != 0.
Also during this deployment, we added Needs Review to the QAStatus list for all datasets, via SQL script.
=> Added else branch, for when FishCount != null and != 0.

DataTracker/js/controllers/controllers.js, DataTracker/js/controllers/dataentry-controllers.js, DataTracker/js/controllers/import-controllers.js, DataTracker/js/controllers/login-controller.js, DataTracker/js/controllers/modals-controller.js, DataTracker/js/controllers/script-controllers.js, DataTracker/js/services.js, DataTracker/partials/invalidOperation/modal-invalid-operation.html
This updated incorporates the following items.
- Updates the frontend routes to call a reorganized C# backend
- Any minor code changes to make the Benthic change work properly
=> Reorg with Benthic Update

DataTracker/partials/subproject/modal-create-subproject.html
Added a new person to the list.
=> Updated CRPP ProjectLeads

DataTracker/css/app.css, DataTracker/js/controllers/modals-controller.js, DataTracker/partials/subproject/modal-create-habSubproject.html, DataTracker/partials/subproject/modal-new-correspondenceEvent.html, DataTracker/partials/subproject/modal-new-habitatItem.html
This update includes the following.
- Fixes a problem with Habitat Subprojects Editing
- Cleans up the form content alignment on CRPP Subproject, Correspondence Event, Habitat Subproject, and Habitat Item
=> Fix hab subp edit issue

DataTracker/partials/subproject/modal-create-subproject.html, DataTracker/partials/subproject/modal-new-correspondenceEvent.html
Verifying all changes are clear.
=> Verify changes

app/core/datasets/components/dataset-entry-form/templates/dataset-entry-form.html
Adjust positioning on Data Entry Page of Instrument box.
=> Additional upd

app/core/common/common-functions.js, app/core/datasets/components/dataset-import/dataset-import.js, app/core/datasets/components/dataset-import/templates/dataset-import.html, app/core/datasets/services/datasheet.js
WaterTemp Duplicate Checking Fix
This update fixes a problem, where the Water Temp Dupe checking code caught the duplicates, but it did not turn the applicable rows red.
=> Wt dupe fix

app/core/datasets/datasets-functions.js
- FIX: control type of 'currency' is now properly configured for the ng-grid to notice updates to the field.
=> Fix currency field

app/private/habitat/components/habitat-sites/templates/modal-new-habitatItem.html
- Add "Monitoring Data" to "Item Type" dropdown field on the new item modal of habitat sites.
=> add monitoring data option to habitat sites item type list

app/core/datasets/components/dataset-activities-list/dataset-activities-list.js
This update restores the Edit link on the Dataset Activities page, and has an associated backend also.
=> Creel Survey Update

app/core/common/services/common-service.js, app/core/datasets/components/dataset-activities-list/templates/dataset-activities.html, app/core/datasets/components/dataset-entry-form/dataset-entry-form.js
- Fish Transport location now shows up (NOTE: there is a config.js file change necessary (see below))
- Benthic and Drift locations now appear
config.js on DEV, TEST, PROD will need to have: 
var LOCATION_TYPE_FishTransport = 118;
=> Location fixes

app/core/common/components/file/modal-files.js, app/core/datasets/components/dataset-entry-form/dataset-entry-form.js, app/core/datasets/services/activity-parser.js
CreelSurvey, DataEntry page, button Add Section does not save the activity -- fixed.
=> Fixed CreelSurvey Add Section save problem.

app/core/datasets/components/dataset-entry-form/dataset-entry-form.js, app/core/datasets/services/activity-parser.js
Commented out some debug lines.
=> CreelSurvey Add Section

app/core/common/components/modals/templates/modal-addlocation.html, app/core/common/directives/validation.js, app/core/datasets/components/dataset-entry-form/dataset-entry-form.js, app/core/datasets/datasets-functions.js, app/core/datasets/services/datasheet.js, assets/js/ag-grid-enterprise.js, bower_components/ag-grid-enterprise/dist/ag-grid-enterprise.js
The update does the following.
-Add/Edit Location Modal requires four-digit elevation; fixed (any integer will work now)
-On Data Entry page, unable to save a new instrument; fixed
=> WaterTemp Import Problem

app/core/common/services/common-service.js, app/core/datasets/components/dataset-editor/dataset-edit-form.js, app/core/datasets/components/dataset-entry-form/dataset-entry-form.js, app/core/datasets/components/dataset-import/dataset-import.js
This update does the following.
-On the Add/Edit Location modal, the Elevation box requires a 4-digit entry; fixed (allows any whole number)
-On the Data Entry page, unable to add/save a new instrument; fixed
=> Added code to limit the instruments in a combo-box to only active ones.

app/core/datasets/components/dataset-import/dataset-import.js
WaterTemp Dataset Import page, Preview page, when added a new Instrument, the modal does not close:  fixed.
=> Added function postSaveInstrumentUpdateGrid.

app/core/admin/components/admin-page/admin-new-dataset.js
Added code to prevent the user from adding a duplicate dataset to a project.
=> Admin dup dataset fix

app/core/admin/components/admin-page/admin-new-dataset.js, app/core/datasets/components/dataset-entry-form/dataset-entry-form.js, app/core/datasets/components/dataset-import/dataset-import.js
Removed FishScale, Genetic, and Metrics from duplicate checking.
=> Exclude ds from dupe checks
